name: MSML_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - dagshub
      - matplotlib
      - seaborn

